2022-11-12 18:31:24 jdbc[6]: exception
org.h2.jdbc.JdbcSQLNonTransientException: El objeto ya está cerrado
The object is already closed [90007-214]
2022-11-12 18:44:35 jdbc[4]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "PACIENTE" ya existe
Table "PACIENTE" already exists; SQL statement:
CREATE TABLE paciente(id int primary key,nombre varchar (255),apellido varchar (255),dni int ,domicilio varchar (255), fechaAlta varchar (255)) [42101-214]
2022-11-12 18:53:37 jdbc[5]: null
org.h2.message.DbException: La conexión no fue cerrada por la aplicación y esta siendo limpiada (garbage collected)
The connection was not closed by the application and is garbage collected [90018-214]
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.message.DbException.get(DbException.java:188)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:190)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:132)
	at org.h2.Driver.connect(Driver.java:59)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:683)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:230)
	at com.digitalhouse.odontologo.repository.impl.OdontologoDaoH2.getConection(OdontologoDaoH2.java:21)
	at com.digitalhouse.odontologo.repository.impl.OdontologoDaoH2.cargar(OdontologoDaoH2.java:27)
	at com.digitalhouse.odontologo.repository.impl.OdontologoDaoH2.cargar(OdontologoDaoH2.java:11)
	at com.digitalhouse.odontologo.service.OdontologoService.cargar(OdontologoService.java:20)
	at com.digitalhouse.odontologo.OdontologoApplication.main(OdontologoApplication.java:43)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: La conexión no fue cerrada por la aplicación y esta siendo limpiada (garbage collected)
The connection was not closed by the application and is garbage collected [90018-214]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:678)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	... 13 more
2022-11-12 18:53:37 jdbc[5]: null
org.h2.message.DbException: La conexión no fue cerrada por la aplicación y esta siendo limpiada (garbage collected)
The connection was not closed by the application and is garbage collected [90018-214]
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.message.DbException.get(DbException.java:188)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:190)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:132)
	at org.h2.Driver.connect(Driver.java:59)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:683)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:230)
	at com.digitalhouse.odontologo.repository.impl.OdontologoDaoH2.getConection(OdontologoDaoH2.java:21)
	at com.digitalhouse.odontologo.repository.impl.OdontologoDaoH2.cargar(OdontologoDaoH2.java:27)
	at com.digitalhouse.odontologo.repository.impl.OdontologoDaoH2.cargar(OdontologoDaoH2.java:11)
	at com.digitalhouse.odontologo.service.OdontologoService.cargar(OdontologoService.java:20)
	at com.digitalhouse.odontologo.OdontologoApplication.main(OdontologoApplication.java:43)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: La conexión no fue cerrada por la aplicación y esta siendo limpiada (garbage collected)
The connection was not closed by the application and is garbage collected [90018-214]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:678)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	... 13 more
2022-11-12 18:53:37 jdbc[6]: exception
org.h2.jdbc.JdbcSQLNonTransientException: El objeto ya está cerrado
The object is already closed [90007-214]
2022-11-12 18:55:44 jdbc[4]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "ODONTOLOGO" ya existe
Table "ODONTOLOGO" already exists; SQL statement:
CREATE TABLE odontologo(id int primary key,apellido varchar(255),nombre varchar (255),matricula varchar (255)) [42101-214]
2022-11-12 19:03:26 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Error de Sintaxis en sentencia SQL "CREATE TABLE turno(id int primary key,pacienteId int,odontologoId int,fecha varchar (255),confirmacion boolean ,CONSTRAINT FK_odontologoId [*]FOREGIN KEY (odontologoId) REFERENCES odontologo(id),CONSTRAINT FK_pacienteId FOREGIN KEY (pacienteId) REFERENCES paciente(id));"; se esperaba "., COMMENT, PRIMARY, UNIQUE, FOREIGN, CHECK"
Syntax error in SQL statement "CREATE TABLE turno(id int primary key,pacienteId int,odontologoId int,fecha varchar (255),confirmacion boolean ,CONSTRAINT FK_odontologoId [*]FOREGIN KEY (odontologoId) REFERENCES odontologo(id),CONSTRAINT FK_pacienteId FOREGIN KEY (pacienteId) REFERENCES paciente(id));"; expected "., COMMENT, PRIMARY, UNIQUE, FOREIGN, CHECK"; SQL statement:
CREATE TABLE turno(id int primary key,pacienteId int,odontologoId int,fecha varchar (255),confirmacion boolean ,CONSTRAINT FK_odontologoId FOREGIN KEY (odontologoId) REFERENCES odontologo(id),CONSTRAINT FK_pacienteId FOREGIN KEY (pacienteId) REFERENCES paciente(id)); [42001-214]
2022-11-12 19:03:26 jdbc[4]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "TURNO" no encontrada
Table "TURNO" not found; SQL statement:
INSERT INTO turno VALUES(?,?,?,?;?); [42102-214]
2022-11-12 19:05:35 jdbc[4]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Error de Sintaxis en sentencia SQL "INSERT INTO turno VALUES(?,?,?,?[*];?);"; se esperaba "[, ::, AT, FORMAT, *, /, %, +, -, ||, NOT, IS, ILIKE, REGEXP, AND, OR, ,, )"
Syntax error in SQL statement "INSERT INTO turno VALUES(?,?,?,?[*];?);"; expected "[, ::, AT, FORMAT, *, /, %, +, -, ||, NOT, IS, ILIKE, REGEXP, AND, OR, ,, )"; SQL statement:
INSERT INTO turno VALUES(?,?,?,?;?); [42001-214]
2022-11-12 19:10:13 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Columna "FK_pacienteId" no encontrada
Column "FK_pacienteId" not found [42122-214]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.jdbc.JdbcResultSet.getColumnIndex(JdbcResultSet.java:3492)
	at org.h2.jdbc.JdbcResultSet.getInt(JdbcResultSet.java:337)
	at com.digitalhouse.odontologo.repository.impl.TurnoDaoH2.buscar(TurnoDaoH2.java:56)
	at com.digitalhouse.odontologo.repository.impl.TurnoDaoH2.buscar(TurnoDaoH2.java:13)
	at com.digitalhouse.odontologo.service.TurnoService.buscar(TurnoService.java:25)
	at com.digitalhouse.odontologo.OdontologoApplication.main(OdontologoApplication.java:65)
